global:
  scrape_interval:     120s
  evaluation_interval: 120s
  
  external_labels:
      monitor: '4linux'

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 120s

    static_configs:
      - targets: [ 'localhost:9090','cadvisor:8080','node-exporter:9100', 'mysql-exporter:9104', 'dockerd-exporter:9180' , 'rabbitmq:15692' , 'nginx-exporter:9113' ]