version: '3.2'

services:
  grafana:
    image: grafana/grafana:7.5.15
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_SECURITY_ADMIN_PASSWORD=oheehel4eiCaBuphouToovue9aisachi
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
      
volumes:
  grafana_data: