version: '3.2'

services:
  grafana:
    image: grafana/grafana:7.5.15
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_SECURITY_ADMIN_PASSWORD=GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../ssl:/etc/nginx/ssl
      
volumes:
  grafana_data: